-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 14:57:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`oiseau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oiseau` (
  `idOiseau` INT NOT NULL AUTO_INCREMENT,
  `nomOiseau` VARCHAR(100) NULL,
  `acronyme` VARCHAR(10) NULL,
  PRIMARY KEY (`idOiseau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`observationOiseau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`observationOiseau` (
  `idObservationOiseau` INT NOT NULL AUTO_INCREMENT,
  `X` INT NULL,
  `Y` INT NULL,
  `idOiseau` INT NULL,
  PRIMARY KEY (`idObservationOiseau`),
  INDEX `fk_observationOiseau_oiseau_idx` (`idOiseau` ASC),
  CONSTRAINT `fk_observationOiseau_oiseau`
    FOREIGN KEY (`idOiseau`)
    REFERENCES `mydb`.`oiseau` (`idOiseau`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
